### ISSUE TITLE
local yarn and finding z3-solver

### ISSUE THREAD

**Issue by NikolajBjorner** [microsoft/z3guide#117]
I get this style of error when trying a local build

```
Module build failed (from ./node_modules/@docusaurus/mdx-loader/lib/index.js):
Error: z3-js runtime error: 09cc8ed47a911ae4fb3e8b1da3a93ab7bb078593, z3-failed, const x = Z3.Int.const('x');
const y = Z3.Int.const('y');
const model = await Z3.solve(x.gt(2), y.lt(10), x.add(y.mul(2)).eq(7));
model.sexpr(), Error: main.ts (-5,82): Cannot find module 'z3-solver'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?
main.ts (-2,45): Type 'any' has no signatures for which the type argument list is applicable.
    at getOutput (file:///C:/z3guide/website/src/remark/render-code-blocks.mjs:107:15)
    at file:///C:/z3guide/website/src/remark/render-code-blocks.mjs:236:42
    at transformer (file:///C:/z3guide/website/src/remark/render-code-blocks.mjs:271:19)
```

**Comment by pelikhan** [comment]
It's strong mangling right now, need to use z3 apis instead

**Comment by NikolajBjorner** [comment]
The error disappears when I do a git stash.
